#!/bin/bash

#SBATCH --partition=gpu
#SBATCH --gpus=1
#SBATCH --job-name=install_env
#SBATCH --nodes=1
#SBATCH --time=02:00:00
#SBATCH --output=job_logs/slurm_output_%A.out

module purge
module load 2022
module load Anaconda3/2022.05

cd $HOME/transformer_research/

conda env create -f dl2022_gpu.yml
# conda env create -f environment.yml

# source activate autoformer
# pip install requirements.txt
